root = tree.insert(root, 25)
    # root = tree.insert(root, 40)
    # root = tree.insert(root, 35)
    # root = tree.insert(root, 45)
    # root = tree.insert(root, 50)
    # root = tree.insert(root, 15)
    # root = tree.insert(root, 27)